services:
  sqlserver:
    container_name: ecommerce-sql
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Password1
    networks:
      - ecommerce-net

  ecommerce-api:
    container_name: ecommerce-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=ecommerce-sql;Database=ECommerceDb;User Id=sa;Password=YourStrong@Password1;TrustServerCertificate=True;MultipleActiveResultSets=True
      - ConnectionStrings__Redis=ecommerce-redis:6379
      - Serilog__WriteTo__1__Args__serverUrl=http://ecommerce-seq:5341
    depends_on:
      - sqlserver
      - redis
    networks:
      - ecommerce-net

  redis:
    image: redis:alpine
    container_name: ecommerce-redis
    ports:
      - "6379:6379"
    networks:
      - ecommerce-net

  seq:
    image: datalust/seq:latest
    container_name: ecommerce-seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "8081:80"
      - "5341:5341"
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    driver: bridge